### ISSUE TITLE
User's were automatically logged out when using cpanel-logo-to-copyright

### ISSUE THREAD

**Issue by PlanetGamingGG** [VPTOfficial/VistaPanel-Customizations#1]
Upon opening the cPanel with the Initialization and Script pointed correctly, the cPanel will log the user's out after almost finished loading.
This means that this was not caused by PHP as PHP page will not load at all if that's the case and according to my analysis when testing, I founded that this is a bit tricky.

Ad Seciton : FOOTER
#1 Declared Variable and Point Script > Logged Out
#2 Declared Variable but does not point the script > Passed
#3 Point the script without initalization > Passed
#4 Created test-cpanel-logo-to-copyright so the var is declared inside the script > Logged Out
#5 Copy and pasted the entire code to one <script> tag > Logged Out
#6 Declared Variable but does not point the script (Again) > Logged Out
#7 Remove the need to declare var and point script > Logged Out

Note : If the code was executed directly thru console, it will work.

**Comment by PlanetGamingGG** [comment]
This issue has been forwarded to iFastNet and they said that they had no idea what makes the cPanel logs user's out and there's no problem on my code.
They recommend us to debug our code and upon debugging, no error's or warnings from our code was made.
We're currently still testing and debugging the code and waiting for support replies.

**Comment by PCTipsGR** [comment]
According to some new update we received, we might be able to bypass this limit and make the script work.
We will inform you on new updates.

**Comment by mahofficial** [comment]
Seem's like the issue got fixed by @PlanetGamingGG
