### ISSUE TITLE
Where is that "Anywhere"?

### ISSUE THREAD

**Issue by mauwiks** [VPTOfficial/VistaPanel-Customizations#3]
I regret to ask this, but where is exactly ANYWHERE? http://prntscr.com/kwec32

Where can I input the code? I tried to paste the full-code on each file such as privacy.php and login.php (based on the recent custom login, I believe by PlanetCloud), but it did not work.

**Comment by PCTipsGR** [comment]
It means to paste this in either the header or footer ad section of vPanel.

It has nothing to do with the files you mentioned.
