### ISSUE TITLE
Bug in Responsive Domain Search Script

### ISSUE THREAD

**Issue by mahofficial** [VPTOfficial/VistaPanel-Customizations#4]
Hi @PlanetGamingGG , there appear a bug in Responsive domain search script. 

**This bug only occur if we add Responsive Domain Search Script in _Footer, Left sidebar or Right sidebar advert area_ because they load in all the pages but if we add Responsive Domain Search Script in _Header Advert Area_ then the issue will be resolved because header advert area is loaded on Main vPanel Page.**

Here is the screenshot of the bug taken from addon domain option in vpanel. This bug also appear in similar options like sub-domains, aliases, redirects etc. where search bars are present. <img src="https://image.prntscr.com/image/aQNrvsxXQy2bzdQTLh14_w.png"/>
The script is also affecting other search bars present in vpanel.

**Comment by yagizhan49** [comment]
Did you try doing a `CTRL + Shift + R` ? That will purge the cache and do a hard refresh.

**Comment by mahofficial** [comment]
> Did you try doing a `CTRL + Shift + R` ? That will purge the cache and do a hard refresh.

Hard Refresh will not fix it because it's a bug of replacing each and every search bar present in vpanel. :smile: and i tested it by myself.

**Comment by yagizhan49** [comment]
> > Did you try doing a `CTRL + Shift + R` ? That will purge the cache and do a hard refresh.
> 
> Hard Refresh will not fix it because it's a bug of replacing each and every search bar present in vpanel.  and i tested it by myself.

Are you sure it only replaces search bars? :)

**Comment by mahofficial** [comment]
> > > Did you try doing a `CTRL + Shift + R` ? That will purge the cache and do a hard refresh.
> > 
> > 
> > Hard Refresh will not fix it because it's a bug of replacing each and every search bar present in vpanel.  and i tested it by myself.
> 
> Are you sure it only replaces search bars? :)

Yes, it replaces all the bars in vpanel. Check the screenshot adding addon domain search bar is replaced with search domain :)

**Comment by yagizhan49** [comment]
> > > > Did you try doing a `CTRL + Shift + R` ? That will purge the cache and do a hard refresh.
> > > 
> > > 
> > > Hard Refresh will not fix it because it's a bug of replacing each and every search bar present in vpanel.  and i tested it by myself.
> > 
> > 
> > Are you sure it only replaces search bars? :)
> 
> Yes, it replaces all the bars in vpanel. Check the screenshot adding addon domain search bar is replaced with search domain :)

There isn't any icons or buttons lol

**Comment by mahofficial** [comment]
> > > > > Did you try doing a `CTRL + Shift + R` ? That will purge the cache and do a hard refresh.
> > > > 
> > > > 
> > > > Hard Refresh will not fix it because it's a bug of replacing each and every search bar present in vpanel.  and i tested it by myself.
> > > 
> > > 
> > > Are you sure it only replaces search bars? :)
> > 
> > 
> > Yes, it replaces all the bars in vpanel. Check the screenshot adding addon domain search bar is replaced with search domain :)
> 
> There isn't any icons or buttons lol

Yep! maybe because it removes the add-on domain id and added search domain id instead of it. Let me check by adding code in header :smile:

**Comment by mahofficial** [comment]
> > > > > > Did you try doing a `CTRL + Shift + R` ? That will purge the cache and do a hard refresh.
> > > > > 
> > > > > 
> > > > > Hard Refresh will not fix it because it's a bug of replacing each and every search bar present in vpanel.  and i tested it by myself.
> > > > 
> > > > 
> > > > Are you sure it only replaces search bars? :)
> > > 
> > > 
> > > Yes, it replaces all the bars in vpanel. Check the screenshot adding addon domain search bar is replaced with search domain :)
> > 
> > 
> > There isn't any icons or buttons lol
> 
> Yep! maybe because it removes the add-on domain id and added search domain id instead of it. Let me check by adding code in header

Yay! @yagizhan49 adding it in header cause no bug because it header ads load only on main vpanel page :smile:

**Comment by yagizhan49** [comment]
so is this solved?

**Comment by mahofficial** [comment]
> so is this solved?

Only if we put this script in header ads area instead of footer but if we place it in footer than this bug can occur.

**Comment by yagizhan49** [comment]
Maybe we shouldn't count this as bug then :100:

**Comment by yagizhan49** [comment]
Include this in documentation

**Comment by mahofficial** [comment]
Hmmm, okay! let leave this open as open issue. :smile: . I will modify the bug description

**Comment by mahofficial** [comment]
> Include this in documentation

okay!

**Comment by PCTipsGR** [comment]
@PlanetGamingGG what do you mean that it will not work properly on other pages? I thought @mahofficial said that it would work if you put it in header!

**Comment by mahofficial** [comment]
> @PlanetGamingGG what do you mean that it will not work properly on other pages? I thought @mahofficial said that it would work if you put it in header!

By adding this in header the file will only be loaded on main page and only will fix the domain search bar but if we load it in footer then it will be loaded on all the pages causing mess with all the search bar.
