### ISSUE TITLE
Minified JS contains comments

### ISSUE THREAD

**Issue by PlanetGamingGG** [VPTOfficial/VistaPanel-Customizations#5]
This JS is minified (identified by `.min.js`) but it has comments in it.
https://github.com/VPTOfficial/VistaPanel-Customizations/blob/master/change-password-link-text-changer/change-password-link-text-changer.min.js

**Comment by mahofficial** [comment]
Thanks i had just removed comments from minified version and thanks for correcting the syntax errors :+1:
